name: 'Enterprise Approval Engine'
description: 'Enterprise approval workflows with per-group thresholds (X of N), OR logic, and semver tagging'
author: 'jamengual'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  action:
    description: 'Action to perform: request, check, process-comment, close-issue, process-sub-issue-close'
    required: true

  workflow:
    description: 'Name of the workflow from approvals.yml to use'
    required: false

  version:
    description: 'Semver version for tag creation (e.g., 1.2.3 or v1.2.3)'
    required: false

  issue_number:
    description: 'Issue number for check action'
    required: false

  wait:
    description: 'Wait for approval (polling) in check action'
    required: false
    default: 'false'

  timeout:
    description: 'Timeout for waiting (e.g., 24h, 1h30m)'
    required: false
    default: '72h'

  token:
    description: 'GitHub token for API operations'
    required: true

  app_id:
    description: 'GitHub App ID for team membership checks'
    required: false

  app_private_key:
    description: 'GitHub App private key for team membership checks'
    required: false

  config_path:
    description: 'Path to approvals.yml config file'
    required: false
    default: '.github/approvals.yml'

  config_repo:
    description: 'External repository for shared config (e.g., org/.github). Config file will be {repo-name}_approvals.yml'
    required: false

  issue_action:
    description: 'Issue event action (closed, reopened) for close-issue action'
    required: false

  # Sub-issue processing
  closed_by:
    description: 'Username who closed the sub-issue'
    required: false

  event_action:
    description: 'Event action (closed, reopened) for process-sub-issue-close'
    required: false

  # Jira Integration
  jira_base_url:
    description: 'Jira Cloud base URL (e.g., https://yourcompany.atlassian.net)'
    required: false

  jira_user_email:
    description: 'Jira user email for API authentication'
    required: false

  jira_api_token:
    description: 'Jira API token for authentication'
    required: false

  jira_update_fix_version:
    description: 'Update Jira issues with Fix Version on approval'
    required: false
    default: 'true'

  # Deployment Tracking
  create_deployment:
    description: 'Create GitHub deployment for tracking in deployment dashboard'
    required: false
    default: 'true'

  deployment_environment:
    description: 'Target environment for deployment tracking (e.g., production, staging)'
    required: false
    default: 'production'

  deployment_environment_url:
    description: 'URL to the deployed environment'
    required: false

  # Release Notes
  include_jira_issues:
    description: 'Include Jira issues in approval request body'
    required: false
    default: 'true'

  previous_tag:
    description: 'Previous tag to compare commits against (auto-detected if not specified)'
    required: false

outputs:
  status:
    description: 'Approval status: pending, approved, denied, timeout'

  issue_number:
    description: 'Issue number for the approval request'

  issue_url:
    description: 'URL to the approval issue'

  approvers:
    description: 'Comma-separated list of users who approved'

  denier:
    description: 'User who denied the request'

  tag:
    description: 'Created tag name (if applicable)'

  satisfied_group:
    description: 'Name of the approval group that was satisfied'

  tag_deleted:
    description: 'Tag that was deleted (for close-issue action)'

  # Sub-issue outputs
  parent_issue_number:
    description: 'Parent issue number for sub-issue processing'

  stage_name:
    description: 'Pipeline stage name that was approved/denied'

  next_stage:
    description: 'Next pipeline stage awaiting approval'

  pipeline_complete:
    description: 'Whether the pipeline is complete'

  message:
    description: 'Status message from sub-issue processing'

  # Jira outputs
  jira_issues:
    description: 'Comma-separated list of Jira issue keys in this release'

  jira_issues_json:
    description: 'JSON array of Jira issue details (key, summary, type, status)'

  # Deployment outputs
  deployment_id:
    description: 'GitHub deployment ID for status updates'

  deployment_url:
    description: 'URL to the deployment in GitHub'

  # Release notes
  release_notes:
    description: 'Auto-generated release notes from commits and Jira issues'

  commits_count:
    description: 'Number of commits in this release'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
